---
# This playbook will install stuff.
#
- name: Configure resolv.conf.
  template: src=resolv.conf.j2 dest=/etc/resolv.conf mode=0644 backup=no

- name: Install deltarpm.
  yum: name=deltarpm state=installed
  tags: deltarpm

- name: Install wget.
  yum: name=wget state=installed
  tags: wget

- name: Upgrade all packages.
  yum: name=* state=latest

- name: Install NTP.
  yum: name=ntp state=installed
  tags: ntp

- name: Ensure NTP is running and enabled. 
  service: name=ntpd state=stopped enabled=yes
  tags: ntp

- name: Install tmux.
  yum: name=tmux state=installed
  tags: tmux

- name: Install vim.
  yum: name=vim state=installed
  tags: vim 

- name: install selinux bindings 
  yum: name=libselinux-python state=present 
    
- name: Enable selinux permissive.
  selinux: policy=targeted state=permissive
  tags: selinux

- name: Replace the external network configuration file.
  template: src=ifcfg-ext.j2 dest="/etc/sysconfig/network-scripts/ifcfg-{{ ext_net_name }}" mode=0644 backup=yes

- name: Replace the internal network configuration file.
  template: src=ifcfg-int.j2 dest="/etc/sysconfig/network-scripts/ifcfg-{{ int_net_name }}" mode=0644 backup=yes

- name: Ovewrite hosts file.
  copy: src=hosts dest=/etc/hosts

- name: Overwrite sshd_config.
  copy: src=sshd_config dest=/etc/ssh/sshd_config

- name: Disable and stop NetworkManager.
  service: name=NetworkManager state=stopped enabled=no

- name: Add hostname to the hosts file.
  hostname: name={{ hostname }}

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true
